#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Tool
#
VERSION = 0.1
PACKAGE_NAME = nibtool
TOOL_NAME = nibtool
nibtool_TOOL_ICON = 


#
# Libraries
#
nibtool_LIBRARIES_DEPEND_UPON += -lGormCore -lGorm -lGormObjCHeaderParser 

#
# Resource files
#
nibtool_RESOURCE_FILES = \
Resources/Version \


#
# Header files
#
nibtool_HEADER_FILES = \
NIBTool.h

#
# Class files
#
nibtool_OBJC_FILES = \
NIBTool.m

#
# Other sources
#
nibtool_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
